# Generated by Django 2.0.1 on 2018-06-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=120)),
                ('team', models.CharField(max_length=120)),
                ('title', models.TextField()),
                ('newsType', models.CharField(max_length=120)),
                ('link', models.TextField()),
                ('discription', models.TextField()),
                ('creator', models.CharField(max_length=120)),
                ('new', models.BooleanField()),
                ('visited', models.BooleanField()),
            ],
        ),
    ]
