# Generated by Django 2.0.1 on 2018-06-14 20:58

from django.db import migrations, models
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('parsebot', '0003_flowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredetialsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
    ]
