# Generated by Django 2.0.1 on 2018-06-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsebot', '0004_credetialsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CredetialsModel',
        ),
        migrations.DeleteModel(
            name='FlowModel',
        ),
    ]
