# Generated by Django 2.0.1 on 2018-06-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlbparsebot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MlbTeamArticle',
            new_name='TeamArticle',
        ),
    ]
